services:
  - type: web
    name: qr-code-admin
    runtime: python
    rootDir: admin
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: INTERNAL_API_KEY
        sync: false

  - type: web
    name: qr-code-user
    runtime: python
    rootDir: user
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ADMIN_API_URL
        sync: false
      - key: INTERNAL_API_KEY
        sync: false
